from datetime import date, datetime, timedelta, timezone


UTC = timezone.utc
NOW = datetime.now(UTC)


MOCK_ACCOUNTS: list[dict] = [
    {
        "id": "001A000001",
        "name": "Acme Manufacturing",
        "owner": "Mia Johnson",
        "phone": "+1-415-555-1001",
        "industry": "Manufacturing",
        "website": "https://acme-manufacturing.example",
        "billingCity": "San Francisco",
        "billingCountry": "USA",
        "lastModified": NOW - timedelta(days=1),
    },
    {
        "id": "001A000002",
        "name": "Blue Ocean Retail",
        "owner": "Noah Clarke",
        "phone": "+1-415-555-1002",
        "industry": "Retail",
        "website": "https://blueocean.example",
        "billingCity": "Seattle",
        "billingCountry": "USA",
        "lastModified": NOW - timedelta(days=2),
    },
    {
        "id": "001A000003",
        "name": "Northstar Logistics",
        "owner": "Olivia Smith",
        "phone": "+1-415-555-1003",
        "industry": "Transportation",
        "website": "https://northstar.example",
        "billingCity": "Austin",
        "billingCountry": "USA",
        "lastModified": NOW - timedelta(days=3),
    },
    {
        "id": "001A000004",
        "name": "Greenleaf Foods",
        "owner": "Mia Johnson",
        "phone": "+1-415-555-1004",
        "industry": "Consumer Goods",
        "website": "https://greenleaf.example",
        "billingCity": "Denver",
        "billingCountry": "USA",
        "lastModified": NOW - timedelta(days=4),
    },
    {
        "id": "001A000005",
        "name": "Helios Health",
        "owner": "Ethan Brown",
        "phone": "+1-415-555-1005",
        "industry": "Healthcare",
        "website": "https://helioshealth.example",
        "billingCity": "Boston",
        "billingCountry": "USA",
        "lastModified": NOW - timedelta(days=5),
    },
    {
        "id": "001A000006",
        "name": "Summit Energy",
        "owner": "Noah Clarke",
        "phone": "+1-415-555-1006",
        "industry": "Energy",
        "website": "https://summitenergy.example",
        "billingCity": "Houston",
        "billingCountry": "USA",
        "lastModified": NOW - timedelta(days=6),
    },
    {
        "id": "001A000007",
        "name": "Crescent Bank",
        "owner": "Olivia Smith",
        "phone": "+1-415-555-1007",
        "industry": "Financial Services",
        "website": "https://crescentbank.example",
        "billingCity": "Chicago",
        "billingCountry": "USA",
        "lastModified": NOW - timedelta(days=7),
    },
    {
        "id": "001A000008",
        "name": "Vertex Security",
        "owner": "Ethan Brown",
        "phone": "+1-415-555-1008",
        "industry": "Technology",
        "website": "https://vertexsecurity.example",
        "billingCity": "Portland",
        "billingCountry": "USA",
        "lastModified": NOW - timedelta(days=8),
    },
    {
        "id": "001A000009",
        "name": "Pioneer Media",
        "owner": "Mia Johnson",
        "phone": "+1-415-555-1009",
        "industry": "Media",
        "website": "https://pioneermedia.example",
        "billingCity": "New York",
        "billingCountry": "USA",
        "lastModified": NOW - timedelta(days=9),
    },
    {
        "id": "001A000010",
        "name": "Harbor Telecom",
        "owner": "Noah Clarke",
        "phone": "+1-415-555-1010",
        "industry": "Telecommunications",
        "website": "https://harbortelecom.example",
        "billingCity": "Miami",
        "billingCountry": "USA",
        "lastModified": NOW - timedelta(days=10),
    },
    {
        "id": "001A000011",
        "name": "Falcon Construction",
        "owner": "Olivia Smith",
        "phone": "+1-415-555-1011",
        "industry": "Construction",
        "website": "https://falconbuild.example",
        "billingCity": "Phoenix",
        "billingCountry": "USA",
        "lastModified": NOW - timedelta(days=11),
    },
    {
        "id": "001A000012",
        "name": "Atlas Robotics",
        "owner": "Ethan Brown",
        "phone": "+1-415-555-1012",
        "industry": "Automation",
        "website": "https://atlasrobotics.example",
        "billingCity": "San Jose",
        "billingCountry": "USA",
        "lastModified": NOW - timedelta(days=12),
    },
]


MOCK_OPPORTUNITIES: list[dict] = [
    {
        "id": "006A000001",
        "name": "Acme ERP Expansion",
        "account": "Acme Manufacturing",
        "stageName": "Qualification",
        "amount": 250000.00,
        "closeDate": date.today() + timedelta(days=45),
        "owner": "Mia Johnson",
        "nextStep": "Schedule technical discovery",
        "description": "ERP module rollout for three new plants.",
        "lastModified": NOW - timedelta(hours=5),
    },
    {
        "id": "006A000002",
        "name": "Blue Ocean POS Upgrade",
        "account": "Blue Ocean Retail",
        "stageName": "Proposal/Price Quote",
        "amount": 180000.00,
        "closeDate": date.today() + timedelta(days=21),
        "owner": "Noah Clarke",
        "nextStep": "Finalize discount terms",
        "description": "Nationwide POS terminal refresh.",
        "lastModified": NOW - timedelta(days=1),
    },
    {
        "id": "006A000003",
        "name": "Northstar Route AI",
        "account": "Northstar Logistics",
        "stageName": "Negotiation/Review",
        "amount": 340000.00,
        "closeDate": date.today() + timedelta(days=33),
        "owner": "Olivia Smith",
        "nextStep": "Legal redlines",
        "description": "Optimization platform for fleet operations.",
        "lastModified": NOW - timedelta(days=2),
    },
    {
        "id": "006A000004",
        "name": "Greenleaf Inventory Suite",
        "account": "Greenleaf Foods",
        "stageName": "Needs Analysis",
        "amount": 120000.00,
        "closeDate": date.today() + timedelta(days=56),
        "owner": "Mia Johnson",
        "nextStep": "Prepare ROI model",
        "description": "Warehouse and inventory forecasting package.",
        "lastModified": NOW - timedelta(days=3),
    },
    {
        "id": "006A000005",
        "name": "Helios Compliance Hub",
        "account": "Helios Health",
        "stageName": "Closed Won",
        "amount": 410000.00,
        "closeDate": date.today() - timedelta(days=6),
        "owner": "Ethan Brown",
        "nextStep": "Transition to implementation",
        "description": "Clinical data governance solution.",
        "lastModified": NOW - timedelta(days=4),
    },
    {
        "id": "006A000006",
        "name": "Summit Trading Analytics",
        "account": "Summit Energy",
        "stageName": "Value Proposition",
        "amount": 270000.00,
        "closeDate": date.today() + timedelta(days=60),
        "owner": "Noah Clarke",
        "nextStep": "Security questionnaire",
        "description": "Commodity trading risk analytics.",
        "lastModified": NOW - timedelta(days=5),
    },
    {
        "id": "006A000007",
        "name": "Crescent Data Platform",
        "account": "Crescent Bank",
        "stageName": "Qualification",
        "amount": 590000.00,
        "closeDate": date.today() + timedelta(days=75),
        "owner": "Olivia Smith",
        "nextStep": "Executive workshop",
        "description": "Enterprise data platform migration.",
        "lastModified": NOW - timedelta(days=6),
    },
    {
        "id": "006A000008",
        "name": "Vertex SOC Modernization",
        "account": "Vertex Security",
        "stageName": "Proposal/Price Quote",
        "amount": 310000.00,
        "closeDate": date.today() + timedelta(days=29),
        "owner": "Ethan Brown",
        "nextStep": "Architecture review",
        "description": "Managed SOC tooling and integration.",
        "lastModified": NOW - timedelta(days=7),
    },
]


MOCK_QUOTES: list[dict] = [
    {
        "id": "0Q0A000001",
        "quoteNumber": "Q-10001",
        "name": "Acme Expansion Quote",
        "account": "Acme Manufacturing",
        "opportunity": "Acme ERP Expansion",
        "status": "Draft",
        "grandTotal": 255000.00,
        "expirationDate": date.today() + timedelta(days=30),
        "owner": "Mia Johnson",
        "lastModified": NOW - timedelta(hours=3),
    },
    {
        "id": "0Q0A000002",
        "quoteNumber": "Q-10002",
        "name": "Blue Ocean Upgrade Quote",
        "account": "Blue Ocean Retail",
        "opportunity": "Blue Ocean POS Upgrade",
        "status": "Presented",
        "grandTotal": 178000.00,
        "expirationDate": date.today() + timedelta(days=14),
        "owner": "Noah Clarke",
        "lastModified": NOW - timedelta(days=1),
    },
    {
        "id": "0Q0A000003",
        "quoteNumber": "Q-10003",
        "name": "Northstar AI Quote",
        "account": "Northstar Logistics",
        "opportunity": "Northstar Route AI",
        "status": "Accepted",
        "grandTotal": 342500.00,
        "expirationDate": date.today() + timedelta(days=7),
        "owner": "Olivia Smith",
        "lastModified": NOW - timedelta(days=2),
    },
    {
        "id": "0Q0A000004",
        "quoteNumber": "Q-10004",
        "name": "Vertex SOC Quote",
        "account": "Vertex Security",
        "opportunity": "Vertex SOC Modernization",
        "status": "Draft",
        "grandTotal": 309900.00,
        "expirationDate": date.today() + timedelta(days=20),
        "owner": "Ethan Brown",
        "lastModified": NOW - timedelta(days=3),
    },
]


MOCK_QUOTE_LINE_ITEMS: dict[str, list[dict]] = {
    "0Q0A000001": [
        {
            "id": "0QLI000001",
            "productName": "ERP Core License",
            "quantity": 100,
            "unitPrice": 1500.00,
            "totalPrice": 150000.00,
        },
        {
            "id": "0QLI000002",
            "productName": "Implementation Services",
            "quantity": 1,
            "unitPrice": 105000.00,
            "totalPrice": 105000.00,
        },
    ],
    "0Q0A000002": [
        {
            "id": "0QLI000003",
            "productName": "POS Device Bundle",
            "quantity": 500,
            "unitPrice": 250.00,
            "totalPrice": 125000.00,
        },
        {
            "id": "0QLI000004",
            "productName": "Support Plan",
            "quantity": 12,
            "unitPrice": 4400.00,
            "totalPrice": 52800.00,
        },
    ],
    "0Q0A000003": [
        {
            "id": "0QLI000005",
            "productName": "AI Route Optimization",
            "quantity": 1,
            "unitPrice": 265000.00,
            "totalPrice": 265000.00,
        },
        {
            "id": "0QLI000006",
            "productName": "Training Package",
            "quantity": 1,
            "unitPrice": 77500.00,
            "totalPrice": 77500.00,
        },
    ],
    "0Q0A000004": [],
}


MOCK_LEADS: list[dict] = [
    {
        "id": "00QA000001",
        "name": "Jordan Lee",
        "company": "Aster Labs",
        "status": "Open - Not Contacted",
        "rating": "Hot",
        "owner": "Mia Johnson",
        "createdDate": NOW - timedelta(days=2),
        "email": "jordan.lee@asterlabs.example",
        "phone": "+1-415-555-2001",
        "source": "Web",
    },
    {
        "id": "00QA000002",
        "name": "Avery Carter",
        "company": "Beacon Foods",
        "status": "Working - Contacted",
        "rating": "Warm",
        "owner": "Noah Clarke",
        "createdDate": NOW - timedelta(days=3),
        "email": "avery.carter@beaconfoods.example",
        "phone": "+1-415-555-2002",
        "source": "Event",
    },
    {
        "id": "00QA000003",
        "name": "Taylor Morgan",
        "company": "Catalyst Bio",
        "status": "Qualified",
        "rating": "Hot",
        "owner": "Olivia Smith",
        "createdDate": NOW - timedelta(days=4),
        "email": "taylor.morgan@catalystbio.example",
        "phone": "+1-415-555-2003",
        "source": "Referral",
    },
    {
        "id": "00QA000004",
        "name": "Riley Patel",
        "company": "Delta Capital",
        "status": "Open - Not Contacted",
        "rating": "Cold",
        "owner": "Ethan Brown",
        "createdDate": NOW - timedelta(days=5),
        "email": "riley.patel@deltacapital.example",
        "phone": "+1-415-555-2004",
        "source": "Web",
    },
    {
        "id": "00QA000005",
        "name": "Parker Diaz",
        "company": "Evergreen Logistics",
        "status": "Working - Contacted",
        "rating": "Warm",
        "owner": "Mia Johnson",
        "createdDate": NOW - timedelta(days=6),
        "email": "parker.diaz@evergreenlogistics.example",
        "phone": "+1-415-555-2005",
        "source": "Partner",
    },
    {
        "id": "00QA000006",
        "name": "Alex Kim",
        "company": "Foundry Retail",
        "status": "Qualified",
        "rating": "Hot",
        "owner": "Noah Clarke",
        "createdDate": NOW - timedelta(days=7),
        "email": "alex.kim@foundryretail.example",
        "phone": "+1-415-555-2006",
        "source": "Event",
    },
]
