%% Focused ERD - Finance Integration
erDiagram
  c2g__codaCompany__c }o--|| Account : "c2g__IntercompanyAccount__c"
  c2g__codaCompany__c }o--|| c2g__codaGeneralLedgerAccount__c : "c2g__AuxiliaryGLA__c (+8 more)"
  c2g__codaCreditNote__c }o--|| Account : "c2g__Account__c"
  c2g__codaCreditNote__c }o--|| c2g__codaCompany__c : "c2g__OwnerCompany__c"
  c2g__codaCreditNote__c }o--|| c2g__codaIntercompanyTransfer__c : "c2g__IntercompanyTransfer__c"
  c2g__codaCreditNote__c }o--|| c2g__codaInvoice__c : "c2g__Invoice__c"
  c2g__codaCreditNote__c }o--|| c2g__codaTransaction__c : "c2g__Transaction__c"
  c2g__codaCreditNote__c }o--|| Opportunity : "c2g__Opportunity__c"
  c2g__codaCreditNote__c }o--|| SCMC__Invoicing__c : "SCMFFA__SCM_Invoice__c"
  c2g__codaIntercompanyTransfer__c }o--|| Account : "c2g__SourceDocumentVendorAccount__c"
  c2g__codaIntercompanyTransfer__c }o--|| c2g__codaCompany__c : "c2g__DestinationCompany__c (+1 more)"
  c2g__codaIntercompanyTransfer__c }o--|| c2g__codaCreditNote__c : "c2g__SourceSalesCreditNote__c"
  c2g__codaIntercompanyTransfer__c }o--|| c2g__codaInvoice__c : "c2g__SourceSalesInvoice__c"
  c2g__codaIntercompanyTransferLineItem__c }o--|| Account : "c2g__Account__c (+1 more)"
  c2g__codaIntercompanyTransferLineItem__c }o--|| c2g__codaGeneralLedgerAccount__c : "c2g__GeneralLedgerAccount__c (+1 more)"
  c2g__codaIntercompanyTransferLineItem__c }o--|| c2g__codaIntercompanyTransfer__c : "c2g__IntercompanyTransfer__c"
  c2g__codaInvoice__c }o--|| Account : "c2g__Account__c (+1 more)"
  c2g__codaInvoice__c }o--|| c2g__codaCompany__c : "c2g__OwnerCompany__c"
  c2g__codaInvoice__c }o--|| c2g__codaGeneralLedgerAccount__c : "c2g__GeneralLedgerAccount__c"
  c2g__codaInvoice__c }o--|| c2g__codaIntercompanyTransfer__c : "c2g__IntercompanyTransfer__c"
  c2g__codaInvoice__c }o--|| c2g__codaTransaction__c : "c2g__Transaction__c"
  c2g__codaInvoice__c }o--|| Opportunity : "c2g__Opportunity__c"
  c2g__codaInvoice__c }o--|| SCMC__Invoicing__c : "link_CreateSIN_Id__c (+1 more)"
  c2g__codaJournalLineItem__c }o--|| Account : "c2g__Account__c (+1 more)"
  c2g__codaJournalLineItem__c }o--|| c2g__codaCompany__c : "c2g__DestinationCompany__c (+1 more)"
  c2g__codaJournalLineItem__c }o--|| c2g__codaGeneralLedgerAccount__c : "c2g__GeneralLedgerAccount__c (+1 more)"
  c2g__codaJournalLineItem__c }o--|| c2g__codaIntercompanyTransfer__c : "c2g__IntercompanyTransfer__c"
  c2g__codaJournalLineItem__c }o--|| SCMC__Purchase_Order__c : "FFX_PO__c"
  c2g__codaJournalLineItem__c }o--|| SCMC__Purchase_Order_Line_Item__c : "FFX_POLine__c"
  c2g__codaTransaction__c }o--|| Account : "c2g__Account__c"
  c2g__codaTransaction__c }o--|| c2g__codaCompany__c : "c2g__OwnerCompany__c"
  c2g__codaTransaction__c }o--|| c2g__codaCreditNote__c : "c2g__SalesCreditNote__c"
  c2g__codaTransaction__c }o--|| c2g__codaIntercompanyTransfer__c : "c2g__IntercompanyTransfer__c"
  c2g__codaTransaction__c }o--|| c2g__codaInvoice__c : "c2g__SalesInvoice__c"
  c2g__codaTransaction__c }o--|| SCMC__Purchase_Order__c : "FFX_PO__c"
  c2g__ConsolidationHierarchyLine__c }o--|| c2g__codaCompany__c : "c2g__Company__c (+20 more)"
  Commission_Payment__c }o--|| Account : "Account__c"
  Commission_Payment__c }o--|| c2g__codaInvoice__c : "Sales_Invoice__c"
  Commission_Payment__c }o--|| c2g__codaTransaction__c : "Sales_Invoice_Transaction__c"
  Commission_Payment__c }o--|| Opportunity : "Opportunity__c"
  Commission_Payment__c }o--|| SCMC__Invoicing__c : "OPI_Invoice__c"
  SCMC__Invoicing__c }o--|| Account : "SCMC__Billing_Account__c (+1 more)"
  SCMC__Invoicing__c }o--|| c2g__codaCompany__c : "SCMFFA__Accounting_Company__c"
  SCMC__Invoicing__c }o--|| c2g__codaCreditNote__c : "SCMFFA__Credit_Note__c"
  SCMC__Invoicing__c }o--|| c2g__codaInvoice__c : "link_CreateSIN_Id__c (+1 more)"
  SCMC__Purchase_Order__c }o--|| Account : "SCMC__Procured_for__c"
  SCMC__Purchase_Order__c }o--|| c2g__codaCompany__c : "SCMFFA__Company__c"
  SCMC__Purchase_Order_Line_Item__c }o--|| c2g__codaGeneralLedgerAccount__c : "SCMFFA__General_Ledger_Account__c"
  SCMC__Purchase_Order_Line_Item__c }o--|| SCMC__Purchase_Order__c : "SCMC__Purchase_Order__c"
