%% Focused ERD - Opportunity to Invoicing Flow
erDiagram
  Commission_Payment__c }o--|| Account : "Account__c"
  Commission_Payment__c }o--|| c2g__codaInvoice__c : "Sales_Invoice__c"
  Commission_Payment__c }o--|| Opportunity : "Opportunity__c"
  Commission_Payment__c }o--|| SCMC__Invoicing__c : "OPI_Invoice__c"
  Commission_Payment__c }o--|| SCMC__Sales_Order__c : "SalesOrder__c"
  Commission_Payment__c }o--|| SCMC__Sales_Order_Line_Item__c : "SalesOrderLineItem__c"
  Opportunity_Approval__c }o--|| Opportunity : "Opportunity__c"
  Opportunity_Snapshot__c }o--|| Account : "Account_ID__c"
  Opportunity_Snapshot__c }o--|| Opportunity : "Opportunity_ID__c"
  SCMC__Customer_Quotation__c }o--|| Account : "SCMC__Customer_Account__c (+1 more)"
  SCMC__Customer_Quotation__c }o--|| Contact : "SCMC__Customer_Account_Contact__c"
  SCMC__Customer_Quotation__c }o--|| Opportunity : "SCMC__Opportunity__c"
  SCMC__Customer_Quotation__c }o--|| SCMC__Sales_Order__c : "SCMC__Sales_Order__c"
  SCMC__Customer_Quotation__c }o--|| SCMC__Service_Order__c : "SCMC__Service_Order__c"
  SCMC__Customer_Quotation_Line__c }o--|| SCMC__Customer_Quotation__c : "SCMC__Customer_Quotation__c"
  SCMC__Invoicing__c }o--|| Account : "SCMC__Billing_Account__c (+1 more)"
  SCMC__Invoicing__c }o--|| c2g__codaCompany__c : "SCMFFA__Accounting_Company__c"
  SCMC__Invoicing__c }o--|| c2g__codaCreditNote__c : "SCMFFA__Credit_Note__c"
  SCMC__Invoicing__c }o--|| c2g__codaInvoice__c : "link_CreateSIN_Id__c (+1 more)"
  SCMC__Invoicing__c }o--|| SCMC__Sales_Order__c : "SCMC__Sales_Order__c"
  SCMC__Invoicing__c }o--|| SCMC__Service_Order__c : "SCMC__Service_Contract__c"
  SCMC__Purchase_Order__c }o--|| Account : "SCMC__Procured_for__c"
  SCMC__Purchase_Order__c }o--|| c2g__codaCompany__c : "SCMFFA__Company__c"
  SCMC__Purchase_Order__c }o--|| Contact : "Deliver_To__c"
  SCMC__Purchase_Order__c }o--|| SCMC__Sales_Order__c : "SCMC__Sales_Order__c"
  SCMC__Purchase_Order__c }o--|| SCMC__Service_Order__c : "SCMC__Service_Contract__c"
  SCMC__Purchase_Order_Line_Item__c }o--|| SCMC__Purchase_Order__c : "SCMC__Purchase_Order__c"
  SCMC__Purchase_Order_Line_Item__c }o--|| SCMC__Sales_Order_Line_Item__c : "SCMC__Sales_Order_Line_Item__c"
  SCMC__Receipt__c }o--|| SCMC__Purchase_Order__c : "SCMC__Purchase_Order__c"
  SCMC__Receipt_Line__c }o--|| SCMC__Purchase_Order_Line_Item__c : "SCMC__Purchase_Order_Line_Item__c"
  SCMC__Receipt_Line__c }o--|| SCMC__Receipt__c : "SCMC__Receiver__c"
  SCMC__Sales_Order__c }o--|| Account : "Account__c (+2 more)"
  SCMC__Sales_Order__c }o--|| c2g__codaCompany__c : "SCMFFA__Company__c"
  SCMC__Sales_Order__c }o--|| Contact : "Invoice_To__c (+2 more)"
  SCMC__Sales_Order__c }o--|| Opportunity : "link_Opp2SO_Id__c"
  SCMC__Sales_Order__c }o--|| SCMC__Customer_Quotation__c : "SCMC__Customer_Quotation__c"
  SCMC__Sales_Order_Line_Item__c }o--|| Contact : "Recipient__c"
  SCMC__Sales_Order_Line_Item__c }o--|| SCMC__Customer_Quotation_Line__c : "SCMC__Customer_Quotation_Line__c"
  SCMC__Sales_Order_Line_Item__c }o--|| SCMC__Purchase_Order_Line_Item__c : "SCMC__Purchase_Order_Line_Item__c"
  SCMC__Sales_Order_Line_Item__c }o--|| SCMC__Sales_Order__c : "SCMC__Sales_Order__c"
  SCMC__Service_Order__c }o--|| Account : "SCMC__Customer_Account_Sold_To__c (+2 more)"
  SCMC__Service_Order__c }o--|| c2g__codaCompany__c : "SCMFFA__Company__c"
  SCMC__Service_Order__c }o--|| SCMC__Customer_Quotation__c : "SCMC__Current_Customer_Quotation__c (+1 more)"
  SCMC__Service_Order__c }o--|| SCMC__Sales_Order__c : "SCMC__Sales_Order__c"
